// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartServer.Ef;

namespace SmartServer.Ef.Migrations
{
    [DbContext(typeof(SmartServerContext))]
    [Migration("20200526163458_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("SmartServer.Ef.Models.StoredSmartTemperatureClient", b =>
                {
                    b.Property<Guid>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Discovered")
                        .HasColumnType("TEXT");

                    b.HasKey("DbId");

                    b.ToTable("SmartTemperatureClients");
                });
#pragma warning restore 612, 618
        }
    }
}
