homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 247
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  temperature_unit: C

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
logbook: !include logbook.yaml

frontend:
config:
discovery:
conversation:
history:
  include:
    entities:
      - device_tracker.joba
      - sensor.room_humidity
      - sensor.room_temperature
map:
sun:
cloud:

updater:
  include_used_components: true

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

device_tracker:
  - platform: fritz
    new_device_defaults:
      track_new_devices: true
      hide_if_away: true

history_graph:
  sensors:
    name: Sensors
    entities:
      - sensor.Room_Temperature
      - sensor.Server_CPU_Temperatur
      - sensor.yahoo_temperature
      - sensor.yahoo_humidity
      - sensor.yahoo_pressure
    hours_to_show: 24
    refresh: 60

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 100
zone 2:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 50

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

mqtt:
  password: !secret mqtt_password

tts:
  - platform: google

weather:
  - platform: yweather
    name: Stuttgart Weather