version: '3.3'
services:
    smartserver:
        image: serverlein/smartserver:latest
        restart: always
        environment:
            BrokerAddress: '192.168.188.24'
        ports:
            - "1883:1883"
            - "2000:80"